version: '3'

# Load environment variables from .env file
dotenv: ['.env']

vars:
  BINARY_NAME: gin-sample

tasks:
  # Development
  dev:
    desc: Start dev environment (dependencies + hot reload)
    deps: [docker:up]
    cmd: air

  run:
    desc: Run the server
    cmd: go run cmd/server/main.go

  build:
    desc: Build the binary
    cmd: go build -o {{.BINARY_NAME}} cmd/server/main.go

  test:
    desc: Run tests
    cmd: go test -v ./...

  sync:
    desc: Sync dependencies
    cmd: go mod tidy

  seed:
    desc: Seed database with test data
    deps: [docker:up]
    cmd: go run cmd/seed/main.go

  index:
    desc: Create MongoDB indexes
    deps: [docker:up]
    cmd: go run cmd/index/main.go

  # Docker
  docker:up:
    desc: Start dependencies (MongoDB, Redis, MinIO)
    cmd: docker compose up -d

  docker:prod:
    desc: Start full stack including app (production-like)
    cmd: docker compose --profile prod up -d --build

  docker:down:
    desc: Stop Docker services
    cmd: docker compose --profile prod down

  docker:logs:
    desc: View Docker logs
    cmd: docker compose logs -f

  # Setup
  setup:
    desc: Install git hooks (run once after clone)
    cmd: lefthook install

  # Utilities
  lint:
    desc: Run linter (requires golangci-lint)
    cmd: golangci-lint run

  fmt:
    desc: Format code
    cmd: go fmt ./...

  swagger:
    desc: Generate swagger docs
    cmd: swag init -g cmd/server/main.go -o swagger
