// Code generated by MockGen. DO NOT EDIT.
// Source: gin-sample/internal/repository (interfaces: UserRepository,RefreshTokenRepository,TeamRepository,TeamMemberRepository,TeamInvitationRepository,VoiceMemoRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_repositories.go -package=mocks gin-sample/internal/repository UserRepository,RefreshTokenRepository,TeamRepository,TeamMemberRepository,TeamInvitationRepository,VoiceMemoRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "gin-sample/internal/models"
	reflect "reflect"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, user)
}

// Delete mocks base method.
func (m *MockUserRepository) Delete(ctx context.Context, id primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserRepository)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockUserRepository) FindAll(ctx context.Context) ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockUserRepositoryMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockUserRepository)(nil).FindAll), ctx)
}

// FindByEmail mocks base method.
func (m *MockUserRepository) FindByEmail(ctx context.Context, email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", ctx, email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockUserRepositoryMockRecorder) FindByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockUserRepository)(nil).FindByEmail), ctx, email)
}

// FindByID mocks base method.
func (m *MockUserRepository) FindByID(ctx context.Context, id primitive.ObjectID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserRepository)(nil).FindByID), ctx, id)
}

// Update mocks base method.
func (m *MockUserRepository) Update(ctx context.Context, id primitive.ObjectID, update *models.UpdateUserRequest) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, update)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(ctx, id, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), ctx, id, update)
}

// MockRefreshTokenRepository is a mock of RefreshTokenRepository interface.
type MockRefreshTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockRefreshTokenRepositoryMockRecorder is the mock recorder for MockRefreshTokenRepository.
type MockRefreshTokenRepositoryMockRecorder struct {
	mock *MockRefreshTokenRepository
}

// NewMockRefreshTokenRepository creates a new mock instance.
func NewMockRefreshTokenRepository(ctrl *gomock.Controller) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRefreshTokenRepository) Create(ctx context.Context, token *models.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRefreshTokenRepositoryMockRecorder) Create(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRefreshTokenRepository)(nil).Create), ctx, token)
}

// DeleteByToken mocks base method.
func (m *MockRefreshTokenRepository) DeleteByToken(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByToken indicates an expected call of DeleteByToken.
func (mr *MockRefreshTokenRepositoryMockRecorder) DeleteByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByToken", reflect.TypeOf((*MockRefreshTokenRepository)(nil).DeleteByToken), ctx, token)
}

// DeleteByUserID mocks base method.
func (m *MockRefreshTokenRepository) DeleteByUserID(ctx context.Context, userID primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserID indicates an expected call of DeleteByUserID.
func (mr *MockRefreshTokenRepositoryMockRecorder) DeleteByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserID", reflect.TypeOf((*MockRefreshTokenRepository)(nil).DeleteByUserID), ctx, userID)
}

// FindByToken mocks base method.
func (m *MockRefreshTokenRepository) FindByToken(ctx context.Context, token string) (*models.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByToken", ctx, token)
	ret0, _ := ret[0].(*models.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByToken indicates an expected call of FindByToken.
func (mr *MockRefreshTokenRepositoryMockRecorder) FindByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByToken", reflect.TypeOf((*MockRefreshTokenRepository)(nil).FindByToken), ctx, token)
}

// MockTeamRepository is a mock of TeamRepository interface.
type MockTeamRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTeamRepositoryMockRecorder
	isgomock struct{}
}

// MockTeamRepositoryMockRecorder is the mock recorder for MockTeamRepository.
type MockTeamRepositoryMockRecorder struct {
	mock *MockTeamRepository
}

// NewMockTeamRepository creates a new mock instance.
func NewMockTeamRepository(ctrl *gomock.Controller) *MockTeamRepository {
	mock := &MockTeamRepository{ctrl: ctrl}
	mock.recorder = &MockTeamRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamRepository) EXPECT() *MockTeamRepositoryMockRecorder {
	return m.recorder
}

// CountByOwnerID mocks base method.
func (m *MockTeamRepository) CountByOwnerID(ctx context.Context, ownerID primitive.ObjectID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByOwnerID", ctx, ownerID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByOwnerID indicates an expected call of CountByOwnerID.
func (mr *MockTeamRepositoryMockRecorder) CountByOwnerID(ctx, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByOwnerID", reflect.TypeOf((*MockTeamRepository)(nil).CountByOwnerID), ctx, ownerID)
}

// Create mocks base method.
func (m *MockTeamRepository) Create(ctx context.Context, team *models.Team) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, team)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTeamRepositoryMockRecorder) Create(ctx, team any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTeamRepository)(nil).Create), ctx, team)
}

// FindByID mocks base method.
func (m *MockTeamRepository) FindByID(ctx context.Context, id primitive.ObjectID) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockTeamRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockTeamRepository)(nil).FindByID), ctx, id)
}

// FindBySlug mocks base method.
func (m *MockTeamRepository) FindBySlug(ctx context.Context, slug string) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySlug", ctx, slug)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySlug indicates an expected call of FindBySlug.
func (mr *MockTeamRepositoryMockRecorder) FindBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySlug", reflect.TypeOf((*MockTeamRepository)(nil).FindBySlug), ctx, slug)
}

// FindByUserID mocks base method.
func (m *MockTeamRepository) FindByUserID(ctx context.Context, userID primitive.ObjectID, page, limit int) ([]models.Team, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID, page, limit)
	ret0, _ := ret[0].([]models.Team)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockTeamRepositoryMockRecorder) FindByUserID(ctx, userID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockTeamRepository)(nil).FindByUserID), ctx, userID, page, limit)
}

// SoftDelete mocks base method.
func (m *MockTeamRepository) SoftDelete(ctx context.Context, id primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockTeamRepositoryMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockTeamRepository)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockTeamRepository) Update(ctx context.Context, team *models.Team) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, team)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTeamRepositoryMockRecorder) Update(ctx, team any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTeamRepository)(nil).Update), ctx, team)
}

// MockTeamMemberRepository is a mock of TeamMemberRepository interface.
type MockTeamMemberRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTeamMemberRepositoryMockRecorder
	isgomock struct{}
}

// MockTeamMemberRepositoryMockRecorder is the mock recorder for MockTeamMemberRepository.
type MockTeamMemberRepositoryMockRecorder struct {
	mock *MockTeamMemberRepository
}

// NewMockTeamMemberRepository creates a new mock instance.
func NewMockTeamMemberRepository(ctrl *gomock.Controller) *MockTeamMemberRepository {
	mock := &MockTeamMemberRepository{ctrl: ctrl}
	mock.recorder = &MockTeamMemberRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamMemberRepository) EXPECT() *MockTeamMemberRepositoryMockRecorder {
	return m.recorder
}

// CountByTeamID mocks base method.
func (m *MockTeamMemberRepository) CountByTeamID(ctx context.Context, teamID primitive.ObjectID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByTeamID", ctx, teamID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByTeamID indicates an expected call of CountByTeamID.
func (mr *MockTeamMemberRepositoryMockRecorder) CountByTeamID(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByTeamID", reflect.TypeOf((*MockTeamMemberRepository)(nil).CountByTeamID), ctx, teamID)
}

// Create mocks base method.
func (m *MockTeamMemberRepository) Create(ctx context.Context, member *models.TeamMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, member)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTeamMemberRepositoryMockRecorder) Create(ctx, member any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTeamMemberRepository)(nil).Create), ctx, member)
}

// Delete mocks base method.
func (m *MockTeamMemberRepository) Delete(ctx context.Context, teamID, userID primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, teamID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTeamMemberRepositoryMockRecorder) Delete(ctx, teamID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTeamMemberRepository)(nil).Delete), ctx, teamID, userID)
}

// DeleteAllByTeamID mocks base method.
func (m *MockTeamMemberRepository) DeleteAllByTeamID(ctx context.Context, teamID primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllByTeamID", ctx, teamID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllByTeamID indicates an expected call of DeleteAllByTeamID.
func (mr *MockTeamMemberRepositoryMockRecorder) DeleteAllByTeamID(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllByTeamID", reflect.TypeOf((*MockTeamMemberRepository)(nil).DeleteAllByTeamID), ctx, teamID)
}

// FindByTeamAndUser mocks base method.
func (m *MockTeamMemberRepository) FindByTeamAndUser(ctx context.Context, teamID, userID primitive.ObjectID) (*models.TeamMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTeamAndUser", ctx, teamID, userID)
	ret0, _ := ret[0].(*models.TeamMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTeamAndUser indicates an expected call of FindByTeamAndUser.
func (mr *MockTeamMemberRepositoryMockRecorder) FindByTeamAndUser(ctx, teamID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTeamAndUser", reflect.TypeOf((*MockTeamMemberRepository)(nil).FindByTeamAndUser), ctx, teamID, userID)
}

// FindByTeamID mocks base method.
func (m *MockTeamMemberRepository) FindByTeamID(ctx context.Context, teamID primitive.ObjectID) ([]models.TeamMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTeamID", ctx, teamID)
	ret0, _ := ret[0].([]models.TeamMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTeamID indicates an expected call of FindByTeamID.
func (mr *MockTeamMemberRepositoryMockRecorder) FindByTeamID(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTeamID", reflect.TypeOf((*MockTeamMemberRepository)(nil).FindByTeamID), ctx, teamID)
}

// FindByUserID mocks base method.
func (m *MockTeamMemberRepository) FindByUserID(ctx context.Context, userID primitive.ObjectID) ([]models.TeamMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID)
	ret0, _ := ret[0].([]models.TeamMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockTeamMemberRepositoryMockRecorder) FindByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockTeamMemberRepository)(nil).FindByUserID), ctx, userID)
}

// UpdateRole mocks base method.
func (m *MockTeamMemberRepository) UpdateRole(ctx context.Context, teamID, userID primitive.ObjectID, role string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRole", ctx, teamID, userID, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRole indicates an expected call of UpdateRole.
func (mr *MockTeamMemberRepositoryMockRecorder) UpdateRole(ctx, teamID, userID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRole", reflect.TypeOf((*MockTeamMemberRepository)(nil).UpdateRole), ctx, teamID, userID, role)
}

// MockTeamInvitationRepository is a mock of TeamInvitationRepository interface.
type MockTeamInvitationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTeamInvitationRepositoryMockRecorder
	isgomock struct{}
}

// MockTeamInvitationRepositoryMockRecorder is the mock recorder for MockTeamInvitationRepository.
type MockTeamInvitationRepositoryMockRecorder struct {
	mock *MockTeamInvitationRepository
}

// NewMockTeamInvitationRepository creates a new mock instance.
func NewMockTeamInvitationRepository(ctrl *gomock.Controller) *MockTeamInvitationRepository {
	mock := &MockTeamInvitationRepository{ctrl: ctrl}
	mock.recorder = &MockTeamInvitationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamInvitationRepository) EXPECT() *MockTeamInvitationRepositoryMockRecorder {
	return m.recorder
}

// CountPendingByTeamID mocks base method.
func (m *MockTeamInvitationRepository) CountPendingByTeamID(ctx context.Context, teamID primitive.ObjectID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPendingByTeamID", ctx, teamID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPendingByTeamID indicates an expected call of CountPendingByTeamID.
func (mr *MockTeamInvitationRepositoryMockRecorder) CountPendingByTeamID(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPendingByTeamID", reflect.TypeOf((*MockTeamInvitationRepository)(nil).CountPendingByTeamID), ctx, teamID)
}

// Create mocks base method.
func (m *MockTeamInvitationRepository) Create(ctx context.Context, invitation *models.TeamInvitation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, invitation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTeamInvitationRepositoryMockRecorder) Create(ctx, invitation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTeamInvitationRepository)(nil).Create), ctx, invitation)
}

// Delete mocks base method.
func (m *MockTeamInvitationRepository) Delete(ctx context.Context, id primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTeamInvitationRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTeamInvitationRepository)(nil).Delete), ctx, id)
}

// DeleteAllByTeamID mocks base method.
func (m *MockTeamInvitationRepository) DeleteAllByTeamID(ctx context.Context, teamID primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllByTeamID", ctx, teamID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllByTeamID indicates an expected call of DeleteAllByTeamID.
func (mr *MockTeamInvitationRepositoryMockRecorder) DeleteAllByTeamID(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllByTeamID", reflect.TypeOf((*MockTeamInvitationRepository)(nil).DeleteAllByTeamID), ctx, teamID)
}

// DeleteExpired mocks base method.
func (m *MockTeamInvitationRepository) DeleteExpired(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockTeamInvitationRepositoryMockRecorder) DeleteExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockTeamInvitationRepository)(nil).DeleteExpired), ctx)
}

// FindByEmail mocks base method.
func (m *MockTeamInvitationRepository) FindByEmail(ctx context.Context, email string) ([]models.TeamInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", ctx, email)
	ret0, _ := ret[0].([]models.TeamInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockTeamInvitationRepositoryMockRecorder) FindByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockTeamInvitationRepository)(nil).FindByEmail), ctx, email)
}

// FindByID mocks base method.
func (m *MockTeamInvitationRepository) FindByID(ctx context.Context, id primitive.ObjectID) (*models.TeamInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.TeamInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockTeamInvitationRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockTeamInvitationRepository)(nil).FindByID), ctx, id)
}

// FindByTeamAndEmail mocks base method.
func (m *MockTeamInvitationRepository) FindByTeamAndEmail(ctx context.Context, teamID primitive.ObjectID, email string) (*models.TeamInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTeamAndEmail", ctx, teamID, email)
	ret0, _ := ret[0].(*models.TeamInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTeamAndEmail indicates an expected call of FindByTeamAndEmail.
func (mr *MockTeamInvitationRepositoryMockRecorder) FindByTeamAndEmail(ctx, teamID, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTeamAndEmail", reflect.TypeOf((*MockTeamInvitationRepository)(nil).FindByTeamAndEmail), ctx, teamID, email)
}

// FindByTeamID mocks base method.
func (m *MockTeamInvitationRepository) FindByTeamID(ctx context.Context, teamID primitive.ObjectID) ([]models.TeamInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTeamID", ctx, teamID)
	ret0, _ := ret[0].([]models.TeamInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTeamID indicates an expected call of FindByTeamID.
func (mr *MockTeamInvitationRepositoryMockRecorder) FindByTeamID(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTeamID", reflect.TypeOf((*MockTeamInvitationRepository)(nil).FindByTeamID), ctx, teamID)
}

// MockVoiceMemoRepository is a mock of VoiceMemoRepository interface.
type MockVoiceMemoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVoiceMemoRepositoryMockRecorder
	isgomock struct{}
}

// MockVoiceMemoRepositoryMockRecorder is the mock recorder for MockVoiceMemoRepository.
type MockVoiceMemoRepositoryMockRecorder struct {
	mock *MockVoiceMemoRepository
}

// NewMockVoiceMemoRepository creates a new mock instance.
func NewMockVoiceMemoRepository(ctrl *gomock.Controller) *MockVoiceMemoRepository {
	mock := &MockVoiceMemoRepository{ctrl: ctrl}
	mock.recorder = &MockVoiceMemoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVoiceMemoRepository) EXPECT() *MockVoiceMemoRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVoiceMemoRepository) Create(ctx context.Context, memo *models.VoiceMemo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, memo)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockVoiceMemoRepositoryMockRecorder) Create(ctx, memo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVoiceMemoRepository)(nil).Create), ctx, memo)
}

// FindByID mocks base method.
func (m *MockVoiceMemoRepository) FindByID(ctx context.Context, id primitive.ObjectID) (*models.VoiceMemo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.VoiceMemo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockVoiceMemoRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockVoiceMemoRepository)(nil).FindByID), ctx, id)
}

// FindByTeamID mocks base method.
func (m *MockVoiceMemoRepository) FindByTeamID(ctx context.Context, teamID primitive.ObjectID, page, limit int) ([]models.VoiceMemo, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTeamID", ctx, teamID, page, limit)
	ret0, _ := ret[0].([]models.VoiceMemo)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByTeamID indicates an expected call of FindByTeamID.
func (mr *MockVoiceMemoRepositoryMockRecorder) FindByTeamID(ctx, teamID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTeamID", reflect.TypeOf((*MockVoiceMemoRepository)(nil).FindByTeamID), ctx, teamID, page, limit)
}

// FindByUserID mocks base method.
func (m *MockVoiceMemoRepository) FindByUserID(ctx context.Context, userID primitive.ObjectID, page, limit int) ([]models.VoiceMemo, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID, page, limit)
	ret0, _ := ret[0].([]models.VoiceMemo)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockVoiceMemoRepositoryMockRecorder) FindByUserID(ctx, userID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockVoiceMemoRepository)(nil).FindByUserID), ctx, userID, page, limit)
}

// SoftDeleteByID mocks base method.
func (m *MockVoiceMemoRepository) SoftDeleteByID(ctx context.Context, id primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteByID indicates an expected call of SoftDeleteByID.
func (mr *MockVoiceMemoRepositoryMockRecorder) SoftDeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteByID", reflect.TypeOf((*MockVoiceMemoRepository)(nil).SoftDeleteByID), ctx, id)
}

// SoftDeleteByTeamID mocks base method.
func (m *MockVoiceMemoRepository) SoftDeleteByTeamID(ctx context.Context, teamID primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteByTeamID", ctx, teamID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteByTeamID indicates an expected call of SoftDeleteByTeamID.
func (mr *MockVoiceMemoRepositoryMockRecorder) SoftDeleteByTeamID(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteByTeamID", reflect.TypeOf((*MockVoiceMemoRepository)(nil).SoftDeleteByTeamID), ctx, teamID)
}

// SoftDeleteWithOwnership mocks base method.
func (m *MockVoiceMemoRepository) SoftDeleteWithOwnership(ctx context.Context, id, userID primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteWithOwnership", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteWithOwnership indicates an expected call of SoftDeleteWithOwnership.
func (mr *MockVoiceMemoRepositoryMockRecorder) SoftDeleteWithOwnership(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteWithOwnership", reflect.TypeOf((*MockVoiceMemoRepository)(nil).SoftDeleteWithOwnership), ctx, id, userID)
}

// SoftDeleteWithTeam mocks base method.
func (m *MockVoiceMemoRepository) SoftDeleteWithTeam(ctx context.Context, id, teamID primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteWithTeam", ctx, id, teamID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteWithTeam indicates an expected call of SoftDeleteWithTeam.
func (mr *MockVoiceMemoRepositoryMockRecorder) SoftDeleteWithTeam(ctx, id, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteWithTeam", reflect.TypeOf((*MockVoiceMemoRepository)(nil).SoftDeleteWithTeam), ctx, id, teamID)
}

// UpdateStatus mocks base method.
func (m *MockVoiceMemoRepository) UpdateStatus(ctx context.Context, id primitive.ObjectID, status models.VoiceMemoStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockVoiceMemoRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockVoiceMemoRepository)(nil).UpdateStatus), ctx, id, status)
}

// UpdateStatusConditional mocks base method.
func (m *MockVoiceMemoRepository) UpdateStatusConditional(ctx context.Context, id primitive.ObjectID, fromStatus, toStatus models.VoiceMemoStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusConditional", ctx, id, fromStatus, toStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusConditional indicates an expected call of UpdateStatusConditional.
func (mr *MockVoiceMemoRepositoryMockRecorder) UpdateStatusConditional(ctx, id, fromStatus, toStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusConditional", reflect.TypeOf((*MockVoiceMemoRepository)(nil).UpdateStatusConditional), ctx, id, fromStatus, toStatus)
}

// UpdateStatusWithOwnership mocks base method.
func (m *MockVoiceMemoRepository) UpdateStatusWithOwnership(ctx context.Context, id, userID primitive.ObjectID, fromStatus, toStatus models.VoiceMemoStatus) (*models.VoiceMemo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusWithOwnership", ctx, id, userID, fromStatus, toStatus)
	ret0, _ := ret[0].(*models.VoiceMemo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatusWithOwnership indicates an expected call of UpdateStatusWithOwnership.
func (mr *MockVoiceMemoRepositoryMockRecorder) UpdateStatusWithOwnership(ctx, id, userID, fromStatus, toStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusWithOwnership", reflect.TypeOf((*MockVoiceMemoRepository)(nil).UpdateStatusWithOwnership), ctx, id, userID, fromStatus, toStatus)
}

// UpdateStatusWithTeam mocks base method.
func (m *MockVoiceMemoRepository) UpdateStatusWithTeam(ctx context.Context, id, teamID primitive.ObjectID, fromStatus, toStatus models.VoiceMemoStatus) (*models.VoiceMemo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusWithTeam", ctx, id, teamID, fromStatus, toStatus)
	ret0, _ := ret[0].(*models.VoiceMemo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatusWithTeam indicates an expected call of UpdateStatusWithTeam.
func (mr *MockVoiceMemoRepositoryMockRecorder) UpdateStatusWithTeam(ctx, id, teamID, fromStatus, toStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusWithTeam", reflect.TypeOf((*MockVoiceMemoRepository)(nil).UpdateStatusWithTeam), ctx, id, teamID, fromStatus, toStatus)
}

// UpdateTranscriptionAndStatus mocks base method.
func (m *MockVoiceMemoRepository) UpdateTranscriptionAndStatus(ctx context.Context, id primitive.ObjectID, transcription string, status models.VoiceMemoStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTranscriptionAndStatus", ctx, id, transcription, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTranscriptionAndStatus indicates an expected call of UpdateTranscriptionAndStatus.
func (mr *MockVoiceMemoRepositoryMockRecorder) UpdateTranscriptionAndStatus(ctx, id, transcription, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTranscriptionAndStatus", reflect.TypeOf((*MockVoiceMemoRepository)(nil).UpdateTranscriptionAndStatus), ctx, id, transcription, status)
}
