// Code generated by MockGen. DO NOT EDIT.
// Source: gin-sample/internal/authz (interfaces: Authorizer)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_authz.go -package=mocks gin-sample/internal/authz Authorizer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthorizer is a mock of Authorizer interface.
type MockAuthorizer struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizerMockRecorder
	isgomock struct{}
}

// MockAuthorizerMockRecorder is the mock recorder for MockAuthorizer.
type MockAuthorizerMockRecorder struct {
	mock *MockAuthorizer
}

// NewMockAuthorizer creates a new mock instance.
func NewMockAuthorizer(ctrl *gomock.Controller) *MockAuthorizer {
	mock := &MockAuthorizer{ctrl: ctrl}
	mock.recorder = &MockAuthorizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizer) EXPECT() *MockAuthorizerMockRecorder {
	return m.recorder
}

// CanPerform mocks base method.
func (m *MockAuthorizer) CanPerform(ctx context.Context, userID, teamID primitive.ObjectID, action string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanPerform", ctx, userID, teamID, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanPerform indicates an expected call of CanPerform.
func (mr *MockAuthorizerMockRecorder) CanPerform(ctx, userID, teamID, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanPerform", reflect.TypeOf((*MockAuthorizer)(nil).CanPerform), ctx, userID, teamID, action)
}

// GetUserRole mocks base method.
func (m *MockAuthorizer) GetUserRole(ctx context.Context, userID, teamID primitive.ObjectID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRole", ctx, userID, teamID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRole indicates an expected call of GetUserRole.
func (mr *MockAuthorizerMockRecorder) GetUserRole(ctx, userID, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRole", reflect.TypeOf((*MockAuthorizer)(nil).GetUserRole), ctx, userID, teamID)
}

// IsMember mocks base method.
func (m *MockAuthorizer) IsMember(ctx context.Context, userID, teamID primitive.ObjectID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMember", ctx, userID, teamID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsMember indicates an expected call of IsMember.
func (mr *MockAuthorizerMockRecorder) IsMember(ctx, userID, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMember", reflect.TypeOf((*MockAuthorizer)(nil).IsMember), ctx, userID, teamID)
}
