// Code generated by MockGen. DO NOT EDIT.
// Source: gin-sample/internal/cache (interfaces: RefreshTokenStore)
//
// Generated by this command:
//
//	mockgen -destination=internal/cache/mocks/mock_refresh_token_store.go -package=mocks gin-sample/internal/cache RefreshTokenStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	cache "gin-sample/internal/cache"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRefreshTokenStore is a mock of RefreshTokenStore interface.
type MockRefreshTokenStore struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenStoreMockRecorder
	isgomock struct{}
}

// MockRefreshTokenStoreMockRecorder is the mock recorder for MockRefreshTokenStore.
type MockRefreshTokenStoreMockRecorder struct {
	mock *MockRefreshTokenStore
}

// NewMockRefreshTokenStore creates a new mock instance.
func NewMockRefreshTokenStore(ctrl *gomock.Controller) *MockRefreshTokenStore {
	mock := &MockRefreshTokenStore{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenStore) EXPECT() *MockRefreshTokenStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRefreshTokenStore) Create(ctx context.Context, familyID string, data *cache.RefreshTokenData, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, familyID, data, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRefreshTokenStoreMockRecorder) Create(ctx, familyID, data, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRefreshTokenStore)(nil).Create), ctx, familyID, data, ttl)
}

// Delete mocks base method.
func (m *MockRefreshTokenStore) Delete(ctx context.Context, familyID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, familyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRefreshTokenStoreMockRecorder) Delete(ctx, familyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRefreshTokenStore)(nil).Delete), ctx, familyID)
}

// Get mocks base method.
func (m *MockRefreshTokenStore) Get(ctx context.Context, familyID string) (*cache.RefreshTokenData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, familyID)
	ret0, _ := ret[0].(*cache.RefreshTokenData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRefreshTokenStoreMockRecorder) Get(ctx, familyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRefreshTokenStore)(nil).Get), ctx, familyID)
}

// Rotate mocks base method.
func (m *MockRefreshTokenStore) Rotate(ctx context.Context, familyID, newTokenHash string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rotate", ctx, familyID, newTokenHash, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rotate indicates an expected call of Rotate.
func (mr *MockRefreshTokenStoreMockRecorder) Rotate(ctx, familyID, newTokenHash, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rotate", reflect.TypeOf((*MockRefreshTokenStore)(nil).Rotate), ctx, familyID, newTokenHash, ttl)
}
