// Code generated by MockGen. DO NOT EDIT.
// Source: gin-sample/pkg/auth (interfaces: RefreshTokenGenerator)
//
// Generated by this command:
//
//	mockgen -destination=pkg/auth/mocks/mock_refresh_token.go -package=mocks gin-sample/pkg/auth RefreshTokenGenerator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRefreshTokenGenerator is a mock of RefreshTokenGenerator interface.
type MockRefreshTokenGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenGeneratorMockRecorder
	isgomock struct{}
}

// MockRefreshTokenGeneratorMockRecorder is the mock recorder for MockRefreshTokenGenerator.
type MockRefreshTokenGeneratorMockRecorder struct {
	mock *MockRefreshTokenGenerator
}

// NewMockRefreshTokenGenerator creates a new mock instance.
func NewMockRefreshTokenGenerator(ctrl *gomock.Controller) *MockRefreshTokenGenerator {
	mock := &MockRefreshTokenGenerator{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenGenerator) EXPECT() *MockRefreshTokenGeneratorMockRecorder {
	return m.recorder
}

// CompareHashes mocks base method.
func (m *MockRefreshTokenGenerator) CompareHashes(hash1, hash2 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompareHashes", hash1, hash2)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CompareHashes indicates an expected call of CompareHashes.
func (mr *MockRefreshTokenGeneratorMockRecorder) CompareHashes(hash1, hash2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompareHashes", reflect.TypeOf((*MockRefreshTokenGenerator)(nil).CompareHashes), hash1, hash2)
}

// ExtractFamilyID mocks base method.
func (m *MockRefreshTokenGenerator) ExtractFamilyID(token string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractFamilyID", token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractFamilyID indicates an expected call of ExtractFamilyID.
func (mr *MockRefreshTokenGeneratorMockRecorder) ExtractFamilyID(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractFamilyID", reflect.TypeOf((*MockRefreshTokenGenerator)(nil).ExtractFamilyID), token)
}

// Generate mocks base method.
func (m *MockRefreshTokenGenerator) Generate() (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Generate indicates an expected call of Generate.
func (mr *MockRefreshTokenGeneratorMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockRefreshTokenGenerator)(nil).Generate))
}

// GenerateWithFamily mocks base method.
func (m *MockRefreshTokenGenerator) GenerateWithFamily(familyID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateWithFamily", familyID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateWithFamily indicates an expected call of GenerateWithFamily.
func (mr *MockRefreshTokenGeneratorMockRecorder) GenerateWithFamily(familyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateWithFamily", reflect.TypeOf((*MockRefreshTokenGenerator)(nil).GenerateWithFamily), familyID)
}

// Hash mocks base method.
func (m *MockRefreshTokenGenerator) Hash(token string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", token)
	ret0, _ := ret[0].(string)
	return ret0
}

// Hash indicates an expected call of Hash.
func (mr *MockRefreshTokenGeneratorMockRecorder) Hash(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockRefreshTokenGenerator)(nil).Hash), token)
}
