// Code generated by MockGen. DO NOT EDIT.
// Source: gin-sample/internal/transcription (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_transcription.go -package=mocks gin-sample/internal/transcription Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Transcribe mocks base method.
func (m *MockService) Transcribe(ctx context.Context, audioKey string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transcribe", ctx, audioKey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transcribe indicates an expected call of Transcribe.
func (mr *MockServiceMockRecorder) Transcribe(ctx, audioKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transcribe", reflect.TypeOf((*MockService)(nil).Transcribe), ctx, audioKey)
}
